### PR TITLE
Improve and update italian translation

### PR DESCRIPTION
**Pull request by ema-pe**
Hi, I really love your application, I'm using it everyday for writing my dreams. I'm using it with english language, but, because I'm from Italy, I think that not all people like to use an application with a foreign language.

What I've done:

* I removed or moved old strings;
* Corrected some error;
* Added new strings.

I also subscribed to two issue related to translations, for every question about italian translation you can ask to me.

### CODE REVIEW

**Comment by gsantner** [comment]
Hi there,

thank you very much and glad you like the application :).

The pull request has an error:

> /home/travis/build/gsantner/markor/app/src/main/res/values-it/strings.xml: Error: Found item String/error_cannot_create_notebook_dir more than one time

**Comment by ema-pe** [comment]
I fixed the error, It was a duplicate string that I forgot to delete during translation.

**Comment by ema-pe** [comment]
> If you have android dev-environment, run gradle lintFlavorDefaultDebug to see errors

I don't have an Android dev-environment, I'm only translate the strings from a text editor. I'm checking all strings now.

**Comment by gsantner** [comment]
Btw, you can do that too directly on your phone ;D

[Translate - with Stringlate](https://lonamiwebs.github.io/stringlate/translate?git=https%3A%2F%2Fgithub.com%2Fgsantner%2Fmarkor.git&mail=gro.xobliam@@rentnasg&name=Markor&web=https%3A%2F%2Fgithub.com%2Fgsantner%2Fmarkor)

**Comment by ema-pe** [comment]
> Btw, you can do that too directly on your phone ;D

Yes, I tried that application, but I prefer working on PC ;)

Now I removed all duplicate strings, if there are other error I'll fix them.

**Comment by gsantner** [comment]
There are some more errors in it :D. I can fix this for now if you want.

Keep in mind, if you do all in a notepad, that you have to proper escape special characters and watch out e.g. duplicated.

e.g. you have to escape `'` as `\'`

**Comment by ema-pe** [comment]
Why in you commit have you copied english translations?

**Comment by gsantner** [comment]
oh, damn :D

**Comment by gsantner** [comment]
its fine now

**Comment by ema-pe** [comment]
Are all special characters escaped?

**Comment by gsantner** [comment]
They were not, but they are now

**Comment by ema-pe** [comment]
Thanks, I promise that next time I'll use a better software to check translation files!

**Comment by gsantner** [comment]
Thanks for contributing!

You don't have to use something different, I use mostly a normal editor too, but you have to know how it works. I think the most problem stuff that can happen, happened in this pr ;D.

**Pull request merged**
