### PR TITLE
Various bugfixes (anchor/toc jumping, snippets folder, wikitext newfile, virtual directory browser)

### PR DESCRIPTION
**Pull request by harshad1**
This addresses several recent bugs:

- #2369 
- #2364 
- #2362 
- #2350

### CODE REVIEW

**Review by gsantner — APPROVED** [review]
Thank you for your fixes and quick changes. I want to release them soon.

**Comment by gsantner** [comment]
On master I noticed that filebrowser dividers are missing in dialogs (i.e. chose Notebook location)

Probably related to your recent question

**Comment by harshad1** [comment]
Yeah. I just noticed it too. I was just going to revert / fix this.

Although, do we just want to remove the dividers?

Screenshot_20240727-102022

The android files app does not have any dividers and looks pretty good

**Comment by gsantner** [comment]
Preferably keep divider

**Pull request merged**
