### PR TITLE
AutoTextFormatter: Fix crashes with very long numbers

### PR DESCRIPTION
**Pull request by harshad1**
When testing the most recent changes I discovered that messing with very long numbers can cause crashes - this fixes the 2 issues I found

### CODE REVIEW

**Comment by gsantner** [comment]
I would includes this as last change for the update and release it then. Though without buzz, 2.10.4.

**Comment by gsantner** [comment]
I would includes this as last change for the update and release it then. Though without buzz, 2.10.4.

Do you have something else around still?

**Comment by gsantner** [comment]
Thank you! I would includes this as last change for the update and release it then. Though without buzz, 2.10.4.

Do you have some other changes around still?

**Comment by gsantner** [comment]
Also fixes  # 1729? Not I guess

**Review by gsantner — APPROVED** [review]

**Comment by harshad1** [comment]
> Do you have some other changes around still?

There is an issue I noticed today where inserting a context / project etc causes the editor to scroll to a different location, I will try to get a fix for this out later this evening my time.

**Comment by gsantner** [comment]
Did various improvements and fixes as well these days. Really hope the 
big refactorings don't lead to too much crashes when released.

**Comment by harshad1** [comment]
> Did various improvements and fixes as well these days. Really hope the big refactorings don't lead to too much crashes when released.

I usually run master on my phone for daily use. So far no issues. I think the refactoring was needed - markor feels even better now. Almost like I have a new phone!

**Pull request merged**
