### PR TITLE
color picker

### PR DESCRIPTION
**Pull request by jakubAerik**
Hi, i am creating pull request on issue "TextAction: color picker #364".

### CODE REVIEW

**Comment by jakubAerik** [comment]
Okay :) but as you written, you didn't want any other libraries to add into project so i decided for this simple/basic result, using alertDialog :) but okay, i will use this library for your project, no problem :) ;)

**Comment by gsantner** [comment]
Oh, I think have described it little too less. I meant that we dont need a big spectecular thing. I know there are HUGE libs out with like 5 different modes, preference for normal and compat, theming fragments and on and on and on. 
Thats what we dont need, just something simple. Something where you get an simple color selection view you can emebed into app, and select colors from.

**Comment by jakubAerik** [comment]
Hi ;) 
I've pushed some changes so please check it and reply me if u'll have time :)

**Comment by gsantner** [comment]
@jakubAerik Thanks for help! And concrats to first-time merged contribution! :) :tada:

**Pull request merged**
