### PR TITLE
(duplicate) Zim-Wiki support nr2 fredericjacob

### LINKED ISSUE #393: Format: Zim Wiki
#### General information

* **App version:** 1.3.0
* **System:** Lineageos microg

#### Description
I was wondering if it would be possible to add support for the zim wiki format. Zim wiki is a notetaking app on desktop. It would be really cool if this app could be the android counterpart to it, using services like syncthing to sync files between them. Here's the site for zim: http://zim-wiki.org

### PR DESCRIPTION
**Pull request by gsantner**
from https://github.com/fredericjacob/markor/tree/zim-highlighting

other impl #1084 , issue #393

### CODE REVIEW

**Comment by gsantner** [comment]
@fredericjacob   
Hey I didn't hear back from you. How is the status of your zim implementation? Would you be interested in joining @pschwede at #1084 ?

**Comment by fredericjacob** [comment]
@gsantner Hi, thanks for creating the PR and for your welcoming words in #393 . I didn't work on the project for the last few days, but I'm still on it. At a first glance, it seems that @pschwede s implementation is already quite ahead of mine and probably contains most, if not all, of my implemented features. However, I will take a closer look and compare the implementations in more depth.

Of course it is pointless to implement alternative implementations for the same basic features. So maybe there is something in #1084 I can help with (@pschwede Let me know if something comes to your mind where we could collaborate.)
Maybe I will also find something myself while digging through the code.

Apart from that, there are other Zim-related useful features that I am looking forward to work on: certain text actions (if not yet implemented), view mode, creating and deleting (sub-)pages, ...
But before starting to work on most of these, it should make sense to wait until the basic Zim (highlighting) PR is finished and then work on top of this.

**Comment by gsantner** [comment]
Ok thanks. Yeah agreeing, also said on other PR - we can do the "basic PR" and on top various smaller ones that i.e. add a new textaction

**Comment by pschwede** [comment]
Hi @fredericjacob. I'd love to collaborate with you.
E.g. your Unit tests and `__marked__` spannable look really useful.
Also, we could check whose regex patterns are the fastest. I took mine directly from the zim-wiki implementation, though.

**Comment by fredericjacob** [comment]
I just looked at the code more thoroughly. Actually, I have to revise my last statement a bit (that #1084 is quite ahead) as I was misled by the pure LOC additions in #1084  . Now I saw that most files in the format/zimwiki package are currently just exact copies of their counterparts in format/markdown, except for few renamings. (The same applies for most test files in format/zimwiki.)

I tried out the app and found that actual highlighting in the editor is not yet working in #1084, while it is in my implementation (#1088) - at least for highlightings and some basic formattings.
However, I see that #1084 already implements a text converter where I don't have an implementation yet. So the view mode is already working with Zim-specific highlightings.

@pschwede My idea is: maybe we can combine our PRs somehow so that we use your progress on the view mode and and mine on the editor highlightings? Still we have to coordinate on the `ZimWikiHighlighterPattern` class, though. @gsantner Would it be possible for us to work together on a single PR?

**Comment by gsantner** [comment]
I welcome help, however you want.

My suggestion is, frederic refactors his code so same filenames/packages and then we merge/overwrite stuff at pschwede one. And as you said, especially highlighter and testcases.

**Comment by fredericjacob** [comment]
All syntax elements from samples/zim-wiki.txt are now being highlighted in the editor (in a basic form). This includes:

- headings (only colored, not yet adapted in size)
- bold
- italics
- marked text (highlighted with a yellow background)
- struck-through text
- preformatted (monospaced) text inline
- preformatted text multiple lines
- unordered lists
- ordered lists
- links
- superscript
- subscript
- checklists (only mono-colored for now, no matter the check state)

I tried to use the colors and styles which are also used in the Zim desktop application.
So this is pretty much ready to be merged with #1084 after some refactoring and coordination with @pschwede. :)

**Review by pschwede — APPROVED** [review]
👍

**Comment by fredericjacob** [comment]
The PR is currently up-to-date with #1084. The size of headings is now adapted according to their level in the editor. Checkboxes are now colored according to their four possible states in Zim (unchecked, checked, crossed, "arrowed").
So highlighting of the basic elements in the editor is pretty complete. Reviews are welcome :)

**Comment by gsantner** [comment]
@fredericjacob  
Please see #1098

OK with that? Otherwise we end up this "split way" the whole time.

**Pull request closed without merging**
