### PR TITLE
Hindi (India) translations of strings

### PR DESCRIPTION
**Pull request by kartikarora**
For issue #20

### CODE REVIEW

**Comment by kartikarora** [comment]
@gsantner You might wanna have a look at [plurals](https://developer.android.com/guide/topics/resources/string-resource.html#Plurals) to manage quantity stirngs, such as on line 60 and 61 of `strings.xml`

**Comment by gsantner** [comment]
Another leftover from the old codebase. You can send a PR for that if you want to

**Comment by kartikarora** [comment]
I can, but then it'll create an issue for other language strings. Its better if you use that concept for future quantity strings and other languages adapt.

**Comment by gsantner** [comment]
Would just add the new plural now, but not yet use it in code, and swap over to it at some point when more is translated

**Comment by kartikarora** [comment]
Ah good idea! PR coming in 5 mins!

**Pull request merged**
