### PR TITLE
Share files from file browser (multiple) #590

### PR DESCRIPTION
**Pull request by kylephelps757**
Let me first say that I am new to github. Any feedback/criticism is welcomed.

Added email button to filesystem_menu
Added askForEmail
Added shareMultipleStream
     used Intent.ACTION_SEND_MULTIPLE and intent.putParcelableArrayListExtra to send multiple files

### CODE REVIEW

**Comment by gsantner** [comment]
@kylephelps757 
thanks! The bot noticed various things already. Run the auto reformat & optimize imports in Android Studio and most noted points will be done automatically

**Comment by kylephelps757** [comment]
I ran the reformat on the whole app with just optimize imports checked. It changed a lot of stuff

**Comment by gsantner** [comment]
@kylephelps757 
Thanks, I see :D . Looks like you also got it on res, not only source code :D.
Would you mind to download <https://github.com/kylephelps757/markor/archive/89c2d50afbd34229c7dbff44c1aaa01df1e4ca6f.zip> and change back the res folder? So only changes are in java folder

**Comment by gsantner** [comment]
@kylephelps757 
Thanks for your work! I'm adding/merging this to Markor now. I will make some minor improvements on it, looks good!

If you want and have time, I'm happy to welcome you again in the project and open for more contributions! If you don't know what todo, take a look at the issue tracker.

:tada:

**Pull request merged**
