### PR TITLE
Fix for Android 4.4 crash when opening .txt files, closes  #1328

### LINKED ISSUE #1328: Android 4.4 ZimWiki detection crash when opening .txt file
#### General information

* **App version: 2.6.0 Google PlayStore** 
* **System:Android 5.0 vs. 4.4** 

#### Description
I cannot open .txt files on my tablet. Only a message '"Markor" wurde beendet' is displayed and Markor is closed. This happens with every .txt file on my tablet with Android 4.4. On my phone with Android 5.0 Markor works fine. 
No difference if I try to open a .txt from Markor's "Files" section or by applying "open with" on a .txt file from an Android file parser. The same file renamed to .md is opened correctly. 
I activated "Experimental features" and "Debug" in Markor settings but could not find a debug log.

### PR DESCRIPTION
**Pull request by fredericjacob**
This PR fixes the issue that Markor crashes when opening .txt files (or creating new .txt files) on Android 4.4, see #1328.

It turned out that in Android 4.4 regexes are more limited compared to newer versions: (At least) in Lookbehind Patterns (i.e. of the form `(?<=(...)`) Android 4.4 only supports bounded quantifiers up to 10 characters (e.g. `{0,10}`). If "longer" quantifiers like `{0,16}` are used, a `PatternSyntaxException` is thrown on attempts to compile the pattern.

A maximum of 10 whitespaces before the bullet point/number of a list item should be more than enough, so I just reduced the amount to 10.

Tested this with an emulator, as I don't have an Android 4.4 device.

### CODE REVIEW

**Comment by gsantner** [comment]
@AnniePerson 

you can download a test apk here <https://github.com/gsantner/markor/actions/runs/823385414>

can you please confirm if it works for you now?

**Comment by AnniePerson** [comment]
Yes, it loads and displays .txt files now on Android 4.4.2

There's a difference:

The released version on Android 5 automatically creates a table of content when it is switched to markdown view.

In the test version the table of content ist missing. Is this the intended behaviour or is it an open issue?

 

Thank you for the quick fix.

 

Best regards

 

Annie Person

 


 

---
______________________________________________________________
Herbert Schneider
***@***.***
http://www.moonlightcrisis.de - http://www.facebook.com/MoonlightCrisis
http://www.frankenbaend.de - http://www.facebook.com/Frankenbaend
http://www.basdjo.de - https://www.facebook.com/Basdjo

 
 

Gesendet: Samstag, 08. Mai 2021 um 20:20 Uhr
Von: "Gregor Santner" ***@***.***>
An: "gsantner/markor" ***@***.***>
Cc: "AnniePerson" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [gsantner/markor] Fix for Android 4.4 crash when opening .txt files, closes #1328 (#1341)


 

@AnniePerson

you can download a test apk here https://github.com/gsantner/markor/actions/runs/823385414

can you please confirm if it works for you now?

**Comment by gsantner** [comment]
markor and mordor are two different apps

**Comment by AnniePerson** [comment]
I was a bit surprised that the app was named Mordor.

 

What went wrong?

The mail I received said

you can download a test apk here https://github.com/gsantner/markor/actions/runs/823385414

I downloaded the zip file, it unpacked to net.gsantner.markor-v122-2.6.0-flavorAtest-debug.apk

The installed app shows up as "Mordor"

---
______________________________________________________________
Herbert Schneider
***@***.***
http://www.moonlightcrisis.de - http://www.facebook.com/MoonlightCrisis
http://www.frankenbaend.de - http://www.facebook.com/Frankenbaend
http://www.basdjo.de - https://www.facebook.com/Basdjo

 
 

Gesendet: Sonntag, 09. Mai 2021 um 09:53 Uhr
Von: "Gregor Santner" ***@***.***>
An: "gsantner/markor" ***@***.***>
Cc: "AnniePerson" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [gsantner/markor] Fix for Android 4.4 crash when opening .txt files, closes #1328 (#1341)


 

markor and mordor are two different apps

**Comment by fredericjacob** [comment]
@AnniePerson Regarding the table of content: You might not have enabled it in the settings: Settings -> Markdown -> Table of Content. (Like @gsantner said, "Mordor" is installed separately)

**Pull request merged**
