### PR TITLE
Implemented Export to PDF for API 19+

### LINKED ISSUE #41: Allow export as PDF
Allow rendered markdown to be exported as pdf

### PR DESCRIPTION
**Pull request by KrishAmal**
PDF Share feature implemented for API 19+ only.

Fixes #41

### CODE REVIEW

**Comment by gsantner** [comment]
Thanks, seems fine so far!

Please use the document-name method on API>21 (as seen here: <https://stackoverflow.com/questions/35261271/createprintdocumentadapter-replacement/42794837#42794837>)

You can use e.g. `String.format("%s (%s)", note.getFilename(), getString(R.string.app_name))` for the document name

**Comment by KrishAmal** [comment]
Sure , thanks for the tip 👍

**Comment by gsantner** [comment]
thanks!

**Comment by gsantner** [comment]
Thanks!

maybe there another one for you <https://github.com/search?&q=label%3Ahacktoberfest+user%3Agsantner>

**Pull request merged**
