### PR TITLE
Mention zim wiki support in F-Droid description

### PR DESCRIPTION
**Pull request by Self-Perfection**

### CODE REVIEW

**Comment by Self-Perfection** [comment]
I hope zim wiki support get to F-Droid, Google Play and https://alternativeto.net/software/markor/about/

AFAIK Markor is the only Android app that supports zim wiki syntax. For now Zim wiki can discover Markor mostly by the grapevine, it is not searchable in F-Droid / Google Play by "zim" keyword.

**Comment by gsantner** [comment]
Would you mind to generally update the readme & f-droid drescription? (Which similary goes to website & others). 

It's not just Zim is missing there 😄

**Comment by gsantner** [comment]
Would you mind to generally update/overhaul the readme & f-droid description? (Which similary goes to website & others). 
It's not just Zim is missing there 😄 .

I'm specifically also interested in what users think and value most at Markor, so there might be things more important to you than to me at Markor.

**Comment by Self-Perfection** [comment]
@gsantner I find current description concise and to the point. I mostly use following Markor features:

1. Zim wiki syntax support
2. Easy syncing via syncthing
3. Sharing text to Markor (using it as a clipboard)

Point 1 was missing, point 2 is already described in substantial details. So after re-reading description I spotted only one possible improvement: clipboard feature description was vague. I tried to improve it.

So that's it. I am surely missing something but I do not pay close attention to changelogs.

**Review by gsantner — APPROVED** [review]
Did a few additions as well. But still it's only F-Droid not readme that is improved.

Anyway, I want to add that change now.

**Pull request merged**
