### PR TITLE
pull request image view from url in popup

### PR DESCRIPTION
**Pull request by noob893796**
Hello, 

Issue: TextAction: Show pictures in a picture view #365
Just finished with loading image from url into popup window.

### CODE REVIEW

**Comment by gsantner** [comment]
hey!

Sorry, but it seems like that we were talking both about different things. The todo was completly about the text editor, not the `representation` aka the webview! 
So the challange in the task was not to intercept picture clicks in web browser, but to extract image filepaths from the current edited textfile, and show them in a popup dialog.
This means you can reused "picture showing / download" code, but no changes at all in webview/webviewclient is needed/wanted.
Places where the new methods / calls should be added are in `TextAction` classes as described in issue. Probably best place is to add it to [CommonTextModuleActions.java](https://github.com/gsantner/markor/blob/master/app/src/main/java/net/gsantner/markor/format/plaintext/CommonTextModuleActions.java). You can for development e.g. comment the `ACTION_OPEN_LINK_BROWSER` case and put your method calls there, then click the `open link in browser button` 
screenshot_20181015-221104

---------
screenshot_20181015-221638


When you now click the button, a image view should come up displaying the image. It should work for both, local images and web (http links) images.


Heres the text I used, you can just copy it to your document.
```
My old schools logo: ![logo1](https://upload.wikimedia.org/wikipedia/de/thumb/2/21/HTL_Braunau_Logo.svg/800px-HTL_Braunau_Logo.svg.png)

some nice ![band image](https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Sum-41-Logo.svg/200px-Sum-41-Logo.svg.png) with further text
```


---------

For representation one can use a lightbox css/js which is not goal of the issue! :)

**Comment by noob893796** [comment]
Working on it, sorry for being slow. It will be done this by the end of the week. :) thank you for patience

**Comment by gsantner** [comment]
You do that in freetime and do it by free will, you can take as much time you want. Thats what I'm doing too here.
I'm not a company boss scheduling somebody's task ;).

**Comment by noob893796** [comment]
Is there anything wrong with this? let me know so I can repair everything needed.

**Comment by gsantner** [comment]
I shortly looked into this now. Thanks very much for working on this! :smile: . Great to see new contributors, and at same time great to see/help new Android  coders ;).

 Current state is that it only works for remote pictures, and it's not checked if it is really a picture (just if it is an URL, but not if it is a png/jpg/.. extension). This is fine for now, for a first version which can be improved in next one if you want.
For this, to be mergable:

* See changes in <https://github.com/gsantner/markor/pull/395/files> and change unncessasary changes back to original state. Notably `build.gradle`, `DocumentRepresentationFragment`, `MarkorWebViewClient`, `gradle.properties`. For this it is easiest to just go [here](https://github.com/noob893796/markor) and download / copy paste original version.
* For UI - make the screen be filled with black background color. Basically this is `width/height = match_parent` in xml and `background=@color/black`.

**Comment by gsantner** [comment]
@noob893796 Thanks for another fix!

I just made another pull request from your code instead of master against the [feature_imageviewer](https://github.com/gsantner/markor/tree/feature_imageviewer) branch, because wanna do some improvements to it before going into master. Thanks much for your work! Happy about any more help, whenever you want feel free to! :smile:

**Pull request merged**
