### PR TITLE
BUGFIX: Using the correct format for correct types

### PR DESCRIPTION
**Pull request by harshad1**
This is a bugfix for #2106. Image and audio links added via the dialog were not being formatted correctly.

### CODE REVIEW

**Comment by harshad1** [comment]
Ah shoot. This wasn't really ready to merge in. Sok I'll create a follow up pr tomorrow.

**Comment by gsantner** [comment]
Oh. I found it initially working and thought it's a important hotfix

**Comment by gsantner** [comment]
Some overview of what users have problems with currently

grafik

**Comment by harshad1** [comment]
Is there some way I can access these and perhaps see tracebacks if there are available?

Thanks
H

Oct 12, 2023 15:37:41 Gregor Santner ***@***.***>:

**Pull request merged**
