### PR TITLE
Attachment improvements v4

### PR DESCRIPTION
**Pull request by harshad1**
This is an additional set of improvements to linking and attaching files. Features are:

1. Search for files from the attach dialog
2. Attach favourite / recent files
3. The ShareInto dialog has been reworked:

If the share into dialog detects a link or file path as one of the lines in the text editor, it will offer to insert a link instead. If we append the text to a file, the links will be automatically formatted as per that format's spec.

This PR is built on my other open PR #2176 so I will wait for it to be merged before fixing issues and merging this one.

### CODE REVIEW

**Comment by gsantner** [comment]
Conflicts now

**Comment by harshad1** [comment]
This is done except for one thing:

Links shared to todo are currently formatted at `name:link`. Alternatives suggestions are welcome.

If this is ok then please merge @gsantner

**Comment by gsantner** [comment]
On first hear not a good idea. Usually titles are not one word and links themself usually contain : too (https://)

Am 2. März 2024 07:48:45 MEZ schrieb Harshad Vedartham ***@***.***>:

**Comment by harshad1** [comment]
Made it `link:<<url>>`

**Comment by gsantner** [comment]
thanks, merged!

**Pull request merged**
