### PR TITLE
Prevent crash on rotate in main activity

### PR DESCRIPTION
**Pull request by harshad1**
_document can be null

### CODE REVIEW

**Review by gsantner — APPROVED** [review]

**Comment by gsantner** [comment]
Guess its new Markor update time soon? (not sure with/without partial HL)

**Comment by harshad1** [comment]
> Guess its new Markor update time soon?

I would like to test for a few more days before the next point release, if that's ok. I want to see if there are further ways to mitigate android's poor filesystem behavior. Perhaps once the Androidx changes are ready?

Partial HL will take a long time yet IMO. There are many edge cases which need to be solved.

**Comment by gsantner** [comment]
The AndroidX PR is to be prepared for upcoming times. I don't have a plan to merge it with the next update(s). Just when really needed and it brings notable improvements somewhere.  
So unlike HL performance, it's not something I'm working on ""to get done"".

**Comment by gsantner** [comment]
The AndroidX PR is to be prepared for upcoming times. I don't have a plan to merge it with the next update(s). Just when really needed and it brings notable improvements somewhere.  
So unlike HL performance, it's not something I'm working on ""to get done"".

Generally it's a major change of the app, and it needs some user testing. It may work fine for me, but don't wanna let this one out and see it breaks everywhere at users.

**Comment by gsantner** [comment]
As I know this one is a really bad issue, in the sense text can get lost...want to release a markor update today.

Is there something from you I can merge for this? If you say, hay nothing is totally broken, it's improving something, but there is still something that can be made better...it's ok when it's not perfect yet.

**Pull request merged**
