### PR TITLE
Fix v2.8.1 saving issues

### PR DESCRIPTION
**Pull request by harshad1**
* Merge Document and DocumentIO classes, debloat
* flush() after write()
* less save/read calls in activitiy lifecycle
* ..

### CODE REVIEW

**Comment by harshad1** [comment]
Issue is that the file is not written before it is read.

The text sent to disk in `onPause` is not the same as the text which is read in `onResume`. If you wait 10s, the process succeeds.

**Comment by harshad1** [comment]
This issue is weirder than I thought.

1. Open file
2. Add text
3. Switch apps
4. Open file in other editor <- new text present
5. Open markor again <- new text gone

**Comment by gsantner** [comment]
then maybe cached string in Document, saveinstancestate or textview?

**Comment by gsantner** [comment]
I wrote DocumentIO stuff from scratch, including undo/redo history, file saving etc. Over time most stuff got replaced by other means (i.e. said undo/redo which worked better in the said textview xlass)

**Comment by gsantner** [comment]
when you are on mainactivity, or editor?

on main its due each of quicknote and todo.txt own lifecycle

**Pull request merged**
