### PR TITLE
issue 2232 Incorrect URL highlighting. Support http/https urls only. …

### PR DESCRIPTION
**Pull request by TimReset**
image

### CODE REVIEW

**Comment by TimReset** [comment]
As discussed - https://github.com/gsantner/markor/discussions/2089

**Comment by gsantner** [comment]
thanks

theres some existing issues/discussions too

**Comment by TimReset** [comment]
I didn't find any open issues.
My discussion https://github.com/gsantner/markor/discussions/2089
And a closed issue https://github.com/gsantner/markor/issues/2149

Do you mean, I can use this discussion 2089 in my pr?
I thought, need to use issues only. Therefore I've created a new issue.

**Comment by gsantner** [comment]
It's fine if there was some chat, be it discussion or issue tab. You can also just open merge request just fixing/adding things, describing it at same time.

I.e. "dummy copy paste issues" are not required :-).

**Comment by gsantner** [comment]
This PR, keep it simple

**Comment by harshad1** [comment]
We add a space after URLs to prevent the terminating parenthesis in a markdown link from being highlighted as part of the link 

```
[foo](http://bar.baz )
                    ^
```

Do we still need that after this PR?

**Comment by TimReset** [comment]
> Do we still need that after this PR?

Looks like no:
https://github.com/gsantner/markor/pull/2233/files#diff-21a9f67a1e35bddaccee5a44933de90dc3b8b51d9b182966762a7fcba9b10f10R17
```
        check("[foo](http://bar.baz )", "http://bar.baz");
        check("[foo](http://bar.baz)", "http://bar.baz");
```

**Review by gsantner — APPROVED** [review]
Thank you very much, merging! 😄

**Pull request merged**
