### PR TITLE
Update Turkish translations

### PR DESCRIPTION
**Pull request by mobile46**

### CODE REVIEW

**Comment by gsantner** [comment]
Not escaped `'` -> `\'` at https://github.com/gsantner/markor/pull/220/files#diff-644e6ed8479f1cfded0b247eafb38ddeR185

Did you use stringlate to translate?

**Comment by mobile46** [comment]
Sorry, I didn't use it and I'll use it after that.

**Comment by gsantner** [comment]
Nono, you can keep whatever you prefer. Just thought it made an error.

**Comment by mobile46** [comment]
OK then. Thanks!

**Comment by gsantner** [comment]
too!

**Pull request merged**
