### PR TITLE
Search callback with position

### PR DESCRIPTION
**Pull request by harshad1**
This PR addresses #1068.

### CODE REVIEW

**Comment by harshad1** [comment]
@gsantner This PR should work. I am testing and doing some cleanup.

**Comment by gsantner** [comment]
OK please let me know when can try

**Comment by harshad1** [comment]
@gsantner This is ready to test and merge, if your tests are good.

**Comment by gsantner** [comment]
OK check tomorrow!

Can you please rename line parameter to lineNo or lineNr?
`SearchOrCustomTextDialogCreator.showMarkdownHeadlineDialog(_activity, origText, (text, line) -> {`

it's just for ambiguousity, code often has things like `for (String line : lines)`.

**Pull request merged**
