### PR TITLE
Highlighting in project and context search

### PR DESCRIPTION
**Pull request by harshad1**
Adds highlighting to the project and context search (long press action)

### CODE REVIEW

**Comment by harshad1** [comment]
@gsantner this PR is ready

**Comment by gsantner** [comment]
yes I know and agree. I just don't merge because I know that it will 100% produce a merge conflict on search pr, which I want to not do atm

**Comment by harshad1** [comment]
👍

**Comment by harshad1** [comment]
@gsantner FYI, I have removed the conflicts between the two ready PRs and the search PR. If you want to merge these in first, you can.

**Comment by harshad1** [comment]
Closing this PR as I am including it in the multi-select PR (causes conflicts otherwise)

**Pull request closed without merging**
