### PR TITLE
[WIP] TextAction: Record audio

### PR DESCRIPTION
**Pull request by ivenk**
This is my attempt at  #367 .

Basically I implemented a simple dialog with the dialogfragment with 3 Buttons Play/Stop, Save, Cancel. I do the recording with androids mediaRecorder. The output format currently is .3gp but that should be simple to change. The audio files are stored in the same folder as the text file. The name is : {original_file_name_without_extension}_audio.3gp . In case of multiple audio files for the same text file the names become : {original_file_name_without_extension}_audio_{increasing_number}.3gp .

The current version satisfies the 4 original targets:
- Create new audio recording button
- Popup dialog which has options for start/stop and cancel
- Save recorded audio in same folder as current document
- Add filename to current cursor position in text

Im open for any ideas how to improve this solution.
What output format would be the best choice ?

### CODE REVIEW

**Comment by ivenk** [comment]
presentation

**Comment by gsantner** [comment]
@ivenk ogg is smaller so I would recommend to go for that, otherwise wav is fine too. But I would not go for 3gp.

For .wav see the [recorddialog](https://github.com/IvanSotelo/RecordDialog/blob/master/recorddialog/src/main/java/com/deskode/recorddialog/RecordDialog.java#L199) for reference how it works. For .ogg it shold be as simple as setting a flag.

**Comment by ivenk** [comment]
@gsantner thank you for your feedback i will try and change it to ogg. 
Currently looking into the layout of the dialog.

I will format the code and merge/rebase once im happy with the rest.

**Comment by gsantner** [comment]
OK! Just as note, simple UI is enough - start/pause/stop and on bottom Cancel/OK

**Comment by ivenk** [comment]
Thank you @gsantner !
I will keep it simple.

**Comment by gsantner** [comment]
sorry that the code review bot is not very mercy 😅

**Comment by gsantner** [comment]
if I have to choose between (ogg + no extra lib) OR (wav + extra lib) I prefer ogg.

**Comment by ivenk** [comment]
No problem! I will fix the formatting issues.

I looked into ogg. However mediarecorder support for ogg was only added in api level 29. [link](https://developer.android.com/reference/android/media/MediaRecorder.OutputFormat.html#OGG)
That is why i decided to go with .wav instead. I could still look into ogg but i don't see a way to avoid an extra lib either way. What are your thoughts on this @gsantner ?

**Comment by gsantner** [comment]
Oh. Right, Sorry.

I just checked out the library and its not maintained since years. Gradle-android is at api24 which tells me not much gonna happen there anymore.

Do you think this sample works? https://stackoverflow.com/a/29148087

**Comment by gsantner** [comment]
Oh. Right, Sorry.

I just checked out the library and its not maintained since years. Gradle-android is at api24 which tells me not much gonna happen there anymore.

Do you think this sample works? https://stackoverflow.com/a/29148087

**Comment by ivenk** [comment]
Don't worry about it ! 😄 
I will take a look at the sample and try it out.

**Comment by gsantner** [comment]
Hey!

I'm working on an own solution, based on OmRecorder too. I'm closing this.

Thanks for checking this out! :)

**Pull request closed without merging**
