### PR TITLE
[WIP] Don't change file extension when saving

### PR DESCRIPTION
**Pull request by manmeet-22**
#37
Added -
- Extensions in Constants.java file
- Edited NoteAcitivty

### CODE REVIEW

**Comment by gsantner** [comment]
there are/will be more supported extensions than 2, thererfore a different approach is needed.

e.g. .txt also

**Comment by gsantner** [comment]
but.. .md will still be default for new documents

**Comment by manmeet-22** [comment]
Ok np, I will look into it. 👍

**Comment by gsantner** [comment]
Are you still working on this?

**Comment by manmeet-22** [comment]
Yes I am but not able to devote full time due to Exams. Will do it soon. If you don't mind?

**Comment by gsantner** [comment]
Me too ;). No, just asking

**Comment by manmeet-22** [comment]
Ok great!!

**Pull request closed without merging**
