### PR TITLE
Encryption: Improve wording of log messages & code

### PR DESCRIPTION
**Pull request by opensource21**
Fixing wrong log-message

### CODE REVIEW

**Comment by gsantner** [comment]
Fixed? Regarding "enrypt" ^^

**Comment by opensource21** [comment]
Sorry what's wrong with encrypt? I don't see a second error.

**Comment by gsantner** [comment]
en **C** rypt

**Comment by opensource21** [comment]
Thanks reviews are so useful.

**Review by gsantner — APPROVED** [review]

**Pull request merged**
