### PR TITLE
App 'Auto' Theme: Theme may not be correctly applied when day/night t…

### PR DESCRIPTION
**Pull request by Samuelgabor**
Fixed auto switching dark/light mode.

### CODE REVIEW

**Comment by gsantner** [comment]
Hello thanks

This is still work in progress right?

I found some debug code and commented code. Overall it looks more like something that may bring  additional issues, especially the resumt & file member variables. remember, rotation may wipe out the variables.

**Comment by gsantner** [comment]
@Samuelgabor ?

**Comment by Samuelgabor** [comment]
Hello. I'll do my best to fix and finish my issues as soon as possible
something like that.

št 12. 11. 2020 o 18:08 Gregor Santner <notifications@github.com>
napísal(a):

**Comment by gsantner** [comment]
closing for now, can always be reopened again when it is ready.

**Pull request closed without merging**
