### PR TITLE
Add support for mermaid flowcharts

### LINKED ISSUE #720: Markdown: Diagrams, Graphs, Flowcharts with Mermaid
#### General information

* **App version:** v2.1
* **System:** v9

#### Description
This hacktoberfest issue is about adding support for [mermaid.js](https://mermaidjs.github.io/) to Markor, which allows to create diagrams via Markdown.

Note that Markor's markdown parser, flexmark also has features for Mermaid. Please have a look at the infos [here (flexmark-extensions wiki)](https://github.com/vsch/flexmark-java/wiki/Extensions) and make use of it.  
**For reference howto integrate** Mermaid: previously KaTex was integrated into Markor, it also has javascript&css files bundled via assets and shows in View mode.

-----------

grafik

-----------

### PR DESCRIPTION
**Pull request by fgtham**
The flexmark GitlabExtension already has support for mermaid flowcharts
etc. This commit adds the required JavaScript asset. Mermaid graphs can
be added as code of type 'mermaid':

``````
```mermaid
flowchart LR
    id1["This is the (text) in the box"]
```
``````

Fixes #720.

### CODE REVIEW

**Comment by gsantner** [comment]
Can you gather the info what is the license of the mermaid-js file? The license notice of it should be also in the license notices file.

**Comment by gsantner** [comment]
Can you please gather the info what is the license of the mermaid-js file?  
The license notice of it should be also in the license notices file.

Have you maybe also a small example around that shows how to use it?  
I think off adding it to some sample/showcase document.

**Comment by fgtham** [comment]
It's released under the [MIT License](https://github.com/mermaid-js/mermaid/blob/develop/LICENSE). I'm not sure which file to add the info to.

**Comment by gsantner** [comment]
[licenses_3rd_party.md at gsantner/markor](https://github.com/gsantner/markor/blob/master/app/src/main/res/raw/licenses_3rd_party.md )

**Review by gsantner — APPROVED** [review]

**Pull request merged**
