### PR TITLE
Override .org file extension to use text mimetype (*/* unrecognized on older devices)

### PR DESCRIPTION
**Pull request by antler5**
Prevents `QuickNote.org` from being filtered out of the QuickNote file-picking dialog.

### CODE REVIEW

**Comment by gsantner** [comment]
Thank you, but if we explicitly make some remapping here..better to somewhat the right type

text/org https://orgmode.org/worg/org-media-type.html

**Comment by antler5** [comment]
Ah, I haven't filled out the device information box that would have been in the template if i'd opened an issue -- i stopped getting android updates many years ago

It's up to you whether that's worth merging a fallback for, but ime there's (evidently) no way for a user who wants this to work around their android's poor mimetype api without forking to extend this list. with that in mind, i don't care what the mimetype is as long as it starts with 'text/' >u<

i think i'm against filtered file-pickers without user-facing toggles in general, but idk java so i stopped when i'd fixed my problem -- maybe another day if that'd be a perferred solution

**Comment by gsantner** [comment]
Does it show up with text/org mime type now on your device, and it properly opens the files in editor on click?

**Review by gsantner — APPROVED** [review]

**Comment by antler5** [comment]
> Does it show up with text/org mime type now on your device, and it properly opens the files in editor on click?

Yep, opens as-expected (in the correct mode)
~I do wonder what would happen if QuickNote was set to a `.jenc` file~

**Pull request merged**
