### PR TITLE
filebrowser: Change notebook folder menu icon to home

### PR DESCRIPTION
**Pull request by harshad1**

### CODE REVIEW

**Comment by harshad1** [comment]
@gsantner This change makes sense to me. Please merge if you agree

**Comment by gsantner** [comment]
My personal opinion is that is's fine to have all "Go to folder X" at same point, and adding more buttons/options isn't that much required.

Unless you have a strong preference, we can ask the people in the discussion what they prefere (thumbs up/down)

**Comment by gsantner** [comment]
My personal opinion is that is's fine to have all "Go to folder X" at same point, and adding more buttons/options isn't that much required.

Unless you have a strong preference, we can ask the people in the discussion what they prefer (thumbs up split out/down keep it grouped)

I leave this here for reference how it looks and what still fits depending on amount of things in top toolbar.

image

**Comment by harshad1** [comment]
Note that the change in this PR only affects the file browser view in main activity

i.e. 
image

**Comment by harshad1** [comment]
@gsantner do you have any further opinions about this PR?

**Comment by gsantner** [comment]
To be honest, I don't really want that in. The toolbar is getting bloated and with each new item, less space for the title

**Comment by harshad1** [comment]
I've reverted the icon position. Only changed the icon

**Pull request merged**
