### PR TITLE
make images fill 100% width of the screen, closes #1769

### PR DESCRIPTION
**Pull request by n-wissam**
Image width is small and not responsive to to fill 100% of available screen width and you can notice that more in landscape mode and on larger screens.
The max-width property defines the maximum width of an image and it works if the image width is larger than the maximum available width . If the image width is smaller than the maximum available width, the max-width property has no effect.

See also <https://github.com/gsantner/markor/discussions/1769>

### CODE REVIEW

**Comment by gsantner** [comment]
this change "width:100%" also means that i.e. a small 32px icon gets full width icon. 

Other ideas?

**Comment by n-wissam** [comment]
> this change "width:100%" also means that i.e. a small 32px icon gets full width icon.

IMHO that's totally fine since images are used mostly in markdown, not icons. and using `width:325px;` makes small 32px icon gets the same width as other images.
I have tried multiple markdown editors on desktop and I don't think  one of them supports resizing images depending on if the image is an icon or a relatively larger image

**Comment by gsantner** [comment]
I'm not sure if generally resize to upscale is good. Setting max-width/height is so it not overshoots.

 But generally if you have a camera picture, its already quite big usually, isnt it? (so it rather is downscaled to fit, then upscaled).

Just about behaviour on my device, with 350px as it is now. Fills 3/4 of width roughly in portrait. So about 420px would be filling already. Screen is fullhd. And when I rotate the screen, still I can see the image in full glance without it being chopped of.  That is the intention behind this.

What I rather would try is a combination of max-width, no fixed width, and a max-vh. Assuming a square 500px img, it would already get width downscaled at portrait. Real small images stay as they are. For landscape, vh can be used to make image fit on screen page, but not sure how likable it is by users - depends on content.

**Comment by n-wissam** [comment]
> And when I rotate the screen, still I can see the image in full glance without it being chopped of. That is the intention behind this.

You are right I can see the image but it's small compared to available screen width like you see in the screenshot below:

IMG_20220722_122634_964



> What I rather would try is a combination of max-width, no fixed width, and a max-vh. Assuming a square 500px img, it would already get width downscaled at portrait. Real small images stay as they are. For landscape, vh can be used to make image fit on screen page, but not sure how likable it is by users - depends on content.

I am sorry I didn't get what you meant here completely but if the purpose is just to scale down larger images and leave smaller images as they are why not stop using `width:325px;`  ?

**Comment by gsantner** [comment]
> I am sorry I didn't get what you meant here completely but if the purpose is just to scale down larger images and leave smaller images as they are why not stop using width:325px; ?

This is what I talked about. Removing 325 and having other means to limit the size to be viewable.

**Comment by gsantner** [comment]
I made changes on my own here and it's on master.

Closing this.

**Review by gsantner — COMMENTED** [review]
I made changes on my own here and it's on master.

Closing this.

**Pull request closed without merging**
