### PR TITLE
fixed #75

### LINKED ISSUE #75: Crash  at net.gsantner.markor.model.MarkorSingleton.getFileFromUri
Crash from google play, Markor v0.1.5:

```

Heute, 13:04 in der App-Version 6
LGE L90 (w7ds), 1024MB RAM, Android 5.0
Bericht 1 von 4
java.lang.RuntimeException: 
 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2331)
 
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2391)
 
  at android.app.ActivityThread.access$800 (ActivityThread.java:151)
 
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1309)
 
  at android.os.Handler.dispatchMessage (Handler.java:102)
 
  at android.os.Looper.loop (Looper.java:135)
 
  at android.app.ActivityThread.main (ActivityThread.java:5349)
 
  at java.lang.reflect.Method.invoke (Native Method)
 
  at java.lang.reflect.Method.invoke (Method.java:372)
 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:908)
 
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:703)
Caused by: java.lang.IllegalArgumentException: 
 
  at java.io.File.checkURI (File.java:220)
 
  at java.io.File.<init> (File.java:177)
 
  at net.gsantner.markor.model.MarkorSingleton.getFileFromUri (MarkorSingleton.java:158)
 
  at net.gsantner.markor.activity.NoteActivity.readFileUriFromIntent (NoteActivity.java:168)
 
  at net.gsantner.markor.activity.NoteActivity.openFromEditAction (NoteActivity.java:152)
 
  at net.gsantner.markor.activity.NoteActivity.onCreate (NoteActivity.java:113)
 
  at android.app.Activity.performCreate (Activity.java:6020)
 
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1105)
 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2284)
```

### PR DESCRIPTION
**Pull request by v4-adi**

### CODE REVIEW

**Comment by gsantner** [comment]
@v4-adi Can you give me a little help on java.io.File and the SupportLib-Filehandler/Content stuff? 

* How can I get to know which I can treat as a modifyable file (in terms of content)?
* How can I get to know if I can modify the filename / path?

The problem is that I get partly `file://` paths aswell as `content://` paths for various intents and differently on different API versions, whereas mostly `content://` paths are just files on external storage, which can be deleted, moved, changed. All library methods are suited for `java.io.File` too. 

I basically remade the core of the app, the editor, which was a lot of work. But I did only work with File in there, as the old code was a very bad mix of both. E.g. opening was partly with file, partly with content, saving was all done using file..

Could you take a look at the current code and tell if me if you expect/cause somewhere a crash? Especially at `Document, DocumentLoader, ShareUtil, DocumentActivity and Document*Fragment`. I tried the app with in combination with various filemanagers and couldn't get a crash yet..but I'm sure there will be some.

**Comment by v4-adi** [comment]
starting from api 24 if you want to share some file with another app, you need to use FileProvider. 

Sure, I will look at the current code and get back to you.

**Comment by gsantner** [comment]
@v4-adi I've created a new issue to sum it up whats missing/not working, #126. If you could take a look into it, it would be very awesome

**Comment by v4-adi** [comment]
@gsantner Thanks for summing it up. I will look into it.

**Comment by gsantner** [comment]
Thank you! I'm currently working on getting Manifest intent-filter's fixed. The file extension filter is wrong currently, and even if corrected it won't work (<https://stackoverflow.com/questions/3400072/pathpattern-to-match-file-extension-does-not-work-if-a-period-exists-elsewhere-i/4621284#4621284>) :D.

**Pull request merged**
