### PR TITLE
Added additional syntax highlighting

### PR DESCRIPTION
**Pull request by jamiet-dev**
Added Task List (gfm)
Fixed Lists
Added specific colors for quotes and lists

https://github.com/gsantner/markor/issues/35

### CODE REVIEW

**Comment by gsantner** [comment]
thanks!

looking into it after uni
 
btw: did you maybe commit by another account? :)

**Comment by jamiet-dev** [comment]
Sure did, thanks for pointing that out :)

**Comment by jamiet-dev** [comment]
I'll address this tonight

**Comment by gsantner** [comment]
Merging now for release, just open a new PR then plz ;)

**Pull request merged**
