### PR TITLE
Upgrade architecture - Android SDK33, AndroidX & MANAGE_EXTERNAL_STORAGE,  closes #1359

### LINKED ISSUE #1359: Migrate to androidx & newer Android architecture
#### General information

* **App version:** 2.x
* **System:** Android 11

#### Description
Remove appcompat from markor and opoc, upgrade to AndroidX. Don't use transformation magic, make adjustments at code & androidx imports.

### PR DESCRIPTION
**Pull request by gsantner**
Preparation of update to latest Android SDK, support libraries, file access & more

### CODE REVIEW

**Comment by gsantner** [comment]
I uploaded a test version to google play and requested the "sensitive" MANAGE_EXTERNAL_STORAGE permission for direct file access.

Uploaded "128 (v2.8.4)" from this branch to public testing.  let's see what google says and if they agree and publish it.

* <https://play.google.com/store/apps/details?id=net.gsantner.markor>
* <https://play.google.com/apps/testing/net.gsantner.markor>

**Comment by gsantner** [comment]
Google disagrees that a document & file manager should have [direct file access](https://support.google.com/googleplay/android-developer/answer/10467955?hl=en). 

At least having one of the written use cases should make the app Eligible to use this access type.  
Markor is at least one of these to my opinion:

* Document management apps
* File management
* Search (On Device)

grafik

Google says Markor is not eligable for it though. I asked for another review, but not looks like they change their mind.

**Comment by gsantner** [comment]
Google denied my appeal request (wow !!appeal!! as like it would be a crime to read files).

image

Thus, I won't waste my time on this project with keeping Google happy anymore - main distribution channel is and continues to be F-Droid. (=No updates for Markor on Google Play anymore)

**Comment by gsantner** [comment]
@harshad1 @fredericjacob For your information

**Review by Dark1616 — DISMISSED** [review]

**Comment by harshad1** [comment]
> Thus, I won't waste my time on this project with keeping Google happy anymore - main distribution channel is and continues to be F-Droid. (=No updates for Markor on Google Play anymore)

Would it be worth it to create a google play version where the notebook is restricted to Markor's app-specific storage?

**Comment by gsantner** [comment]
I don't really want to make a separate version for gplay, with separate type of issues, separate type of questions and people suddenly not being able to edit their existing files anymore.

**Comment by harshad1** [comment]
Fair enough.

Maybe Google will listen if enough people complain :)

Jan. 6, 2022 10:53:00 Gregor Santner ***@***.***>:

**Comment by fredericjacob** [comment]
That's a really weird decision and argumentation for the rejection... Does Google tell apps with integrated cloud service access like Google Drive, Dropbox, etc. to consider "more privacy-friendly options", too? I think as well that Markor matches both the file manager and document manager criteria and thus should be compliant with the policy. Actually direct file access IS required to use Markor in synergy with other apps that access the same data, like synchronization via Syncthing etc.

However, I wouldn't give up on Google Play completely. I think the app could lose a big (especially non-techie) audience otherwise, which would be a shame because Markor is really outstanding in its field in terms of features and development, plus being FOSS... Maybe there's still a way to fight the rejection? Continue to argue why it IS compliant? Or like @harshad1 proposed, deploy a variant to Google Play, but maybe display a hint in the description that full file access is not possible in the Google Play version because of how Google interprets its own policy?

**Comment by fredericjacob** [comment]
> Maybe Google will listen if enough people complain :)

That's another hope I have. I think there were other popular apps that were banned from Google Play in a first place because of some "policy violation", but could celebrate a comeback after some heavy shitstorms on the internet. ;)

**Comment by gsantner** [comment]
> apps that were banned from Google Play

noting: Markor is not banned at gplay, available as is in v2.8. Just can't deploy new updates without removing Markor's reason of existance.

**Comment by Ilithy** [comment]
>> apps that were banned from Google Play
> 
> noting: Markor is not banned at gplay, available as is in v2.8. Just can't deploy new updates without removing Markor's reason of existance.

>Google disagrees that a document & file manager should have direct file access.
>
>At least having one of the written use cases should make the app Eligible to use this access type.
Markor is at least one of these to my opinion:
>
>Document management apps
File management
Search (On Device)

Let me ask you a silly question, why don't you remove the data access manager? Use instead the android content provider to get the URI of the files, and be able to edit them, so Markor will be considered only as a file editor, right?

**Comment by gsantner** [comment]
silly answer: It is very likely users get less features and way less performance (abstract fs is very slow on android). apart from that - resources and time are limited. I don't have time to waste, repeatedly and every year, to re-develop everything again, just to access files. Which anyway works as before, just someone external denies it. Especially, this project has exactly the use Google describes allowed to continue to use normal file access.

If you have to time to waste, please go ahead, work on this, make a pull request and provide a solution which not breaks any use cases of the app. I rather enjoy making good things in the project than spending all my time on making Google happy.

thx

**Comment by gsantner** [comment]
silly answer: It is very likely users get less features and way less performance (abstract fs is very slow on android). apart from that - resources and time are limited. I don't have time to waste, repeatedly and every year, to re-develop everything again, just to access files. Which anyway works as before, just someone external denies it. Especially, this project has exactly the use Google describes allowed to continue to use normal file access.

If you have to time to waste, please go ahead, work on this, make a pull request and provide a solution which not breaks any use cases of the app. I rather enjoy making good things in the project than spending all my time on making Google happy.

Don't forget - Google defines the rules in their house. But Markor is not required to be in that house. There are more than enough other houses.

> so Markor will be considered only as a file editor, right?

Markor is many things. But two are the core uses: File manager & File Editor/Document manager. I don't want to limit & dumb down the project to just editor.

thx

**Comment by Ilithy** [comment]
I respect your point of view, many thanks for your work and sorry, my question was really stupid :-/

**Comment by gsantner** [comment]
No need to sorry, not stupid. I just clarified here as well how the situation is, without sugar coat

**Comment by harshad1** [comment]
FYI, after installing this I had to go into app info and give it full file permissions again.

I installed a release build with my local key

**Comment by gsantner** [comment]
Yes, API30+ not uses the Marshmallow storage one but the ManageExternalStorage in this PR

**Comment by gsantner** [comment]
Google Play has changed the opinion on the files permission now with the 2.10.1 submission and it passed reviews.  
So merging this pull request and thus big, major architecture changes, to be ready for future Android versions and Android features.

**Pull request merged**
