### PR TITLE
Add file description customization for file browser entries (#524)

### PR DESCRIPTION
**Pull request by xuvatilavv**
Suggested in #524.

Added a settings entry to allow a customizable file description. If no format string is configured it uses the locale default date format like before. New format string uses the built-in formatting rules of SimpleDateFormat, just filters for a new entry FS and replaces it with a quoted string including the file size, then passes the format string to SimpleDateFormat directly.

I think it'd be nice if we could default the configured string to locale date format, but I didn't see a way to set that up without manually creating strings for all the formats for each locale. For now, default configuration is an empty string, which shows "Default" on the settings screen.

(Sorry for the cancelled PR, it's been a long time since I've done one and I'm remembering how it works 😅 )

### CODE REVIEW

**Comment by gsantner** [comment]
Hello thanks, I will look into it today or tomorrow after work.

Would you mind to 

* Remove AppSettings and pref_key__file_description_format reference from FilesystemViewerAdapter.java (only that file). I want to keep Markor specifics minimal there. Instead use directly SharedPreferences.getString("pref_key__file_description_format", "default")
* Remove the `*bytes_abbreviated` string ressources. No way they will be translated. Just have `String.format(Locale.getDefault(), "fmt", nr, "B");`
* Move the getHumanReadableByteCountSI function to FileUtils class. --> `public static String getHumanReadableByteCountSI(final long bytes)`

**Comment by xuvatilavv** [comment]
Can do.

For the file size translation, I have found that various languages may use different abbreviations, particularly I've found that French uses "20Ko" instead of "20KB". The only major places I've been able to find that uses these translations are Apple devices and Xamarin, both via an NSByteCountFormatter function, so I'm not sure whether it's standard or expected. Would you still like to remove the possibility of translating them?

**Comment by gsantner** [comment]
Yeah remove please, B/KB/MB/GB is fine.

**Comment by xuvatilavv** [comment]
Alright, I've made the changes you requested.

**Comment by gsantner** [comment]
Did various improvements, merging this now.

Thanks for your help! And congrats for your first-time merged contribution!

**Pull request merged**
