### PR TITLE
Csv doc update

### PR DESCRIPTION
**Pull request by k3b**
Added Screenshots to csv docs

### CODE REVIEW

**Comment by gsantner** [comment]
https://github.com/k3b/markor/blob/csv-doc-update/doc/CSV_README.md

**Comment by gsantner** [comment]
If you want to, you can also start a new section for new Markor version at the updates markdown file, referencing the same images.

**Comment by k3b** [comment]
Can you update the release notes at https://github.com/gsantner/markor/releases/tag/v2.10.9  (i have no permissions to do that)

replace 

> See commits for a overview since last update: https://github.com/gsantner/markor/compare/v2.10.8..v2.10.9

with

> Changes in the release: see https://github.com/gsantner/markor/milestone/16?closed=1

---

> If you want to, you can also start a new section for new Markor version at the updates 
> markdown file, referencing the same images.

ok

**Comment by gsantner** [comment]
It is NEWS.md in the repository

**Comment by k3b** [comment]
@gsantner done

**Comment by k3b** [comment]
The version numbers do not match 

* In README "Markor v2.9" corresponds to 
* programversion "Markor v2.10.8 (145)"

**Comment by gsantner** [comment]
Usually I don't make a entry there for patch versions (last digit). So Only for 2.9.0, 2.10.0, 2.11.0....And so everything that happens at 2.10.1, 2.10.2, 2.10.x...will get into 2.11.0

**Comment by gsantner** [comment]
thanks!

**Pull request merged**
