### PR TITLE
[edu] change location

### PR DESCRIPTION
**Pull request by Shallow-D12**
"add_file" button'location can be changed like this.

### CODE REVIEW

**Comment by harshad1** [comment]
@Shallow-D12 Would you be able to post a screenshot of this change?

**Comment by Shallow-D12** [comment]
> @Shallow-D12 Would you be able to post a screenshot of this change?

button

**Comment by harshad1** [comment]
IMO this increases the chance that the add button will block some of the last item in the explorer view.

Gmail, Fairmail etc all use a compose button to the right (like markor does currently) and I think it works better this way.

**Comment by Shallow-D12** [comment]
> IMO this increases the chance that the add button will block some of the last item in the explorer view.
> 
> Gmail, Fairmail etc all use a compose button to the right (like markor does currently) and I think it works better this way.

But for some left-handers, this layout makes the button hard to press.

**Comment by gsantner** [comment]
see #1679

**Pull request closed without merging**
