### PR TITLE
WIP: View: Back To Top button (feature #514)

### PR DESCRIPTION
**Pull request by rici13**
#514

### CODE REVIEW

**Comment by rici13** [comment]
Created pull request as you commented on the issue :)

**Comment by gsantner** [comment]
thanks :)

**Comment by gsantner** [comment]
(I am posting this to all pull requests)

Hey! Just want to know how you are doing. Do you have issues or have questions? If you wont work on this anymore also let me know please, so I can announce to others its free to take again.
Thanks!

**Comment by rici13** [comment]
Hello

Definitely I will work on this issue. I just do not have much time right now. I think in 2-3 weeks I will complete this issue.

**Comment by rici13** [comment]
Hello

I comitted my solution. :) When user click on the button it brings him to top of document.

**Comment by gsantner** [comment]
@rici13 
Thanks for your help! :D 

I've decided on a slightly different approach (long click toolbar), and worked that out. That works same for all modes

**Comment by xuejianxianzun** [comment]
> @ rici13
> 感谢您的帮助！：D
> 
> 我决定采用一种略有不同的方法（长按工具栏），然后解决了。在所有模式下都一样

Thank you, but this method is too concealed. If I don't find this issue, I will always worry about it.

**Pull request closed without merging**
