### PR TITLE
fix the problem of changing file.ext as file.ext.md(fixes issue #409)

### PR DESCRIPTION
**Pull request by jakeoneijk**
I added the code at loadDocument of DocumentIO(fixes issue #409).
If you want different solution for this, please let me know 👍

### CODE REVIEW

**Comment by jakeoneijk** [comment]
thank you for feedback!!
In case 1(no extension), Is it better to change filename to README.md after saving ?? or keep the name as README(no extension) ??

**Comment by gsantner** [comment]
There are two reasons it can be README:
* When you open an existing file as such -> don't rename
* When you just make a new document (+) -> input README from titlebar, here yes .md gets added automatically

**Comment by jakeoneijk** [comment]
thank you !!
you said you will remove "auto-title" but 
Is it still ok for me to work on this problem??

**Comment by gsantner** [comment]
It's not written in stone yet how stuff will go then, just have some ideas around. [Started on that](https://github.com/gsantner/markor/tree/fslist_rework) but it slowly progresses ^^..

Yes it's fine if you change this now, this won't go away from today to tomorrow.

**Comment by jakeoneijk** [comment]
thank you so much for quick reply :)

**Comment by jakeoneijk** [comment]
Hello I fix the problem.
but In case 2 (When you just make a new document (+) -> input README from titlebar, here yes .md gets added automatically) 
I didn't have to solve the problem because ,In case2,



extraPathIsFolder become true



so this code be activated.



and file has ".md" on it.



so it will go to this case and will not reach to code that I made

**Comment by jakeoneijk** [comment]
@gsantner Is there anything that I should do more of modify??

**Comment by gsantner** [comment]
My computer broke , sorry.

**Pull request merged**
