### PR TITLE
Hide bar when textactions are disabled.

### PR DESCRIPTION
**Pull request by WendlerTech**
Solves #740

### CODE REVIEW

**Comment by gsantner** [comment]
Sorry but thats not the solution.

This way text is below the textactions bar.

Dont remove the margin in xml. But set margin in dp in code for editor, plus setVisibility on textactions.

**Comment by WendlerTech** [comment]
Per your edit, @gsantner, I see you found that the setVisibility was already in place. As I said earlier, I spent a good chunk of time going through all the code & I was unable to find what exactly the problem was. This is most likely due to lack of experience in general &/or lack of experience with this (fairly large) codebase, since I feel like I'm missing something obvious. 

From what I found, the setBarVisible method in TextActions is called appropriately to hide the parent, followed by the DocumentEditFragment class calling applyTextFormat to remove the child. Both are using View.GONE but are behaving as if they're using View.INVISIBLE. 

Also may be worth mentioning that prior to the margin fix, while viewing a saved note (from the Files tab, not QuickNote) & having the bar hidden, the area that the bar takes up would actually duplicate the text underneath it, causing the duplicated text to follow along as a user scrolled up & down until they pulled the keyboard back up. This no longer happens after I removed the margin.

**Comment by gsantner** [comment]
can you find a case where text from editor is below the bar?

**Comment by WendlerTech** [comment]
Prior to removing the margin? Yeah, I just create a new note from the Files tab, using the default settings. Add a lot of text (spanning multiple lines, enough to make the user need to scroll & reaching below where the keyboard comes up to), hide the keyboard, then click within the note to re-activate the keyboard. The bar will now have some "ghosting" from the characters that were underneath it.

**Comment by gsantner** [comment]
Weird :D.
And now its all good?

**Comment by WendlerTech** [comment]
Yep, just by removing this line in the parent ScrollView:

`android:layout_marginBottom="@dimen/textactions_bar_height"`

Everything works. The bar hides appropriately, there's no ghosting, & due to always being able to scroll down, the text is never covered/made inaccessible due to lack of a margin.

**Comment by gsantner** [comment]
OK thanks for your findings and fixes! :)

**Comment by WendlerTech** [comment]
Happy to help! I definitely felt a bit lazy committing only 1 deleted line, but at least I got to explain all the work that went into tracking that 1 line down!

**Comment by gsantner** [comment]
Hehe, its early in morning and I'm only on phone, no computer :D. Didnt have look into codebase, just from what I remember.

**Comment by gsantner** [comment]
@WendlerTech have you expierenced similar like #782  ?

**Comment by WendlerTech** [comment]
@gsantner Hmm, yeah, that does happen. I didn't catch it because in my testing I was only adding a few characters & clicking enter, rather than typing all the way through to the next line. Seems like it only happens when the textactions bar is visible.

Prior to the fix, not only did it leave that awkward space, but it was causing text to duplicate when scrolling, so I still think removing it was the right move. It just needs to be re-added when the bar is showing.

I feel like the ideal fix would be to have a flag that, when the textactions bar is set to hidden, would remove the bottom margin & conversely would re-add it when the bar was set to shown again. However, I don't know of an easy way to edit the xml via code, so we may have to come up with something else.

**Pull request merged**
