### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by xredor**
Nice app. Take a russian rtanslation.

### CODE REVIEW

**Comment by gsantner** [comment]
Hi @xredor 
Thank you very much!

merging.

**Comment by gsantner** [comment]
@xredor Are you okay with translations/localizations to be licensed Creative Commons Zero (<https://creativecommons.org/publicdomain/zero/1.0/deed.de>). I'm using this license in all of my FOSS android apps and want to use it here too for translations. This allows me to swap some translation between projects :). Please give me your okay, otherwise I need to remove russian translation again. Sorry, but I didn't have that in mind at accepting the PR-.

Thanks!

**Comment by xredor** [comment]
Ok. Use any licence you wish. 

20 сентября 2017 г. 0:48:08 GMT+03:00, Gregor Santner <notifications@github.com> пишет:
>@xredor Are you okay with translations/localizations to be licensed
>Creative Commons Zero
>(<https://creativecommons.org/publicdomain/zero/1.0/deed.de>). I'm
>using this license in all of my FOSS android apps and want to use it
>here too for translations. This allows me to swap some translation
>between projects :). Please give me your okay, otherwise I need to
>remove russian translation again. Sorry, but I didn't have that in mind
>at accepting the PR-.
>
>Thanks!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/gsantner/markor/pull/6#issuecomment-330683582

-- 
Простите за краткость, создано в K-9 Mail.

**Comment by gsantner** [comment]
k, thx!

**Comment by gsantner** [comment]
French will be redone by milouse, german by myself and two langs can stay :)

**Pull request merged**
