### PR TITLE
Adjust the value of web. to net.

### PR DESCRIPTION
**Pull request by ricardo-ramos-moura**
Adjust in file AndroidManifest.xml to "net.gsantner.markor.activity.MainActivity"

### CODE REVIEW

**Comment by harshad1** [comment]
What would the effect of this be? (My android dev experience outside markor is pretty minimal)

**Comment by gsantner** [comment]
The top-left activity back button uses that packagename to detect "where to go up to". But we don't have the arrow enabled anywhere so don't know any practical difference either.

(setUpEnabled/setUpAsHomeEnabled/android.R.id.home)

**Comment by gsantner** [comment]
??

**Comment by ricardo-ramos-moura** [comment]
@gsantner I opened this PR because I was debugging on Android version 7.1 (Bug in this android version)
and I noticed it was pointing to a non-existent package.

In the project itself it doesn't affect anything in the execution, I just pointed to the right package for a
question of organization and leave the imports as they should be.

Sorry if I caused any inconvenience, I was just trying to help.

**Comment by gsantner** [comment]
No inconvenience, its helpful, thanks!
 But when you open a merge request without giving a description what it is about, and whats the problem, probably nobody else knows either.

**Comment by ricardo-ramos-moura** [comment]
Yes you are right. My mistake.

**Pull request closed without merging**
