### PR TITLE
View-Mode: Prism codeblock copy to clipboard button, update Mermaid and dark mode, closes #2336 closes #2335 

### LINKED ISSUE #2335: Markdown: Mermaid chart dark mode?
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

I use the Mermaid syntax to draw flowcharts in a Markdown file, and everything displays correctly in light mode. However, in dark mode, the lines of the flowchart are almost invisible. We need to change the arrows and lines of the Mermaid flowchart to white or another light color for dark mode.
dark
white

### Steps to reproduce

1. wirte a Mermaid flowchart in dark theme, then you will see the issue.

### Information

Android version: 12
Device: Redmi K30 Pro Zoom Edition
App Version: v2.12.2 (151)

### Source

Google Play

### Format / File type

Not specific

### Additional info / Log

_No response_

### PR DESCRIPTION
**Pull request by guanglinn**
This PR is related to the discussion #2336 and the issue #2335.

In this PR:
1. Add a button to copy the code block;
2. Support applying dark theme for Mermaid diagrams;
3. Update Mermaid from v10.3.1 to v10.9.1;
4. Add a basic keyboard shortcut Ctrl+Y to redo.

### CODE REVIEW

**Comment by guanglinn** [comment]
## Light theme

2024-07-11-copy-code-block-with-one-click

## Dark theme

2024-07-11-copy-code-block-with-one-click-dark

**Comment by guanglinn** [comment]
Now Markor can support dark theme correctly for Mermaid graph. I think the issue #2335 has been resolved.

**Light theme**



**Dark theme**

**Comment by harshad1** [comment]
Very nice

**Comment by guanglinn** [comment]
Mermaid v10.9.1 is stable, its changelog can be seen [here](https://github.com/mermaid-js/mermaid/releases).

The file `mermaid.min.js` is from `https://registry.npmjs.org/mermaid/-/mermaid-10.9.1.tgz` in website `https://www.jsdelivr.com/package/npm/mermaid`.

**Review by gsantner — APPROVED** [review]
Thank you

**Pull request merged**
