### PR TITLE
Remove ambiguity and streamline checklist items in issue templates

### PR DESCRIPTION
**Pull request by opusforlife2**
That last checklist item is ambiguous. Should you check the box or not if the answer is yes or no? I've changed the wording to make it more straightforward, and also harmonised the two versions in each template.

### CODE REVIEW

**Comment by opusforlife2** [comment]
Changes to files in the `.github` folder, and maybe others, could be excluded from the CI.

**Comment by gsantner** [comment]
The reason it is currently written as it is, is because it's rather ""if you are able to do it, do it please"". Might be that not everybody is able to install some debug apk, or use ADB.

> Changes to files in the .github folder, and maybe others, could be excluded from the CI.

Most changes happen to code. Thats rather a optimization for the very fast minority. Then with some CI configuration format change it suddenly not works anymore and breaks something else. Don't see the need for this specifically.

**Comment by opusforlife2** [comment]
> "if you are able to do it, do it please"

I would suggest stating that explicitly, then. Users sometimes come up with the wildest imaginable interpretations of instructions.

**Comment by gsantner** [comment]
Yeah well unfortunatley reporters often just tick boxes without really doing anything of them.

Or ignoring templates and writing just something without much info.

Or leave out many details.

**Comment by opusforlife2** [comment]
Over at Newpipe we use a `template-ignored` label and close such issues, if you're considering cracking down on such behaviour.

**Comment by opusforlife2** [comment]
Too true.

**Pull request merged**
