### PR TITLE
Update uk (Ukrainian) translation

### PR DESCRIPTION
**Pull request by cl0ne**

### CODE REVIEW

**Comment by gsantner** [comment]
Thanks! (BTW/Note: Ukrainian is not completely translated after merging this, some strings are missing)

**Comment by cl0ne** [comment]
@gsantner Oops, missed some new keys. Don't merge it, please :)

**Comment by cl0ne** [comment]
Fixed

**Comment by gsantner** [comment]
Thats why asking :D.
Thanks!

**Pull request merged**
