### PR TITLE
Plural for quantity string

### PR DESCRIPTION
**Pull request by kartikarora**
As discussed in #56 

Added plurals for english and hindi strings, but haven't used it!

Also, could you please not create a merge commit while accepting a PR? It ruins the git history of the forks while pulling! Thanks!

### CODE REVIEW

**Comment by kartikarora** [comment]
Oh damn I made a mistake! :stuck_out_tongue:

**Comment by gsantner** [comment]
Look again, I think we don't need any re-translation ;)

**Comment by kartikarora** [comment]
Nice! It can be used now! :tada:

**Comment by gsantner** [comment]
ooh, I did that on my master branch instead of your PR...haha

see last commit https://github.com/gsantner/markor

**Comment by kartikarora** [comment]
Ah cool! No worries!

**Pull request closed without merging**
