### PR TITLE
Prevent accessibility and autofill from crashing markor

### PR DESCRIPTION
**Pull request by harshad1**
Autofill, like accessibility, can cause crashes because the _entire text of the editor_ is sent to the autofill service for every change. Sending a large file 10s of times a second can cause a crash.

This PR adds logic to block autofill (not needed for editing a document anyway) when the file is large or on some functions which rapidly change the text.

### CODE REVIEW

**Comment by gsantner** [comment]
merge master into PR branch for failure

**Comment by harshad1** [comment]
@gsantner Subject to the CI system passing, this is ready to go.

**Comment by harshad1** [comment]
@gsantner Whats with the JUnit stage?

**Comment by gsantner** [comment]
I tried to get rid of it already, but github still remembers it somewhere. not even completley removing all builds and ci config removes it.......

**Comment by harshad1** [comment]
> I tried to get rid of it already, but github still remembers it somewhere. not even completley removing all builds and ci config removes it.......

Ah. Wanted to make sure the issue was not with my pr

**Review by gsantner — APPROVED** [review]

**Comment by gsantner** [comment]
Don't mind JUnit, only the the "build" is important. It also runs JUnit testcases. The JUnit github item is/was just for visualization of the testcase output.

**Comment by harshad1** [comment]
Thanks for merging. Do you know approximately when this will make it into a release?

**Comment by gsantner** [comment]
probably when we got zim finished

**Pull request merged**
