### PR TITLE
Editor: Move current/selected line(s) up and down via button (feature #715)

### PR DESCRIPTION
**Pull request by Delko97**
Hello, i created pull request as you asked in comment ... :)

ref #715

### CODE REVIEW

**Comment by Delko97** [comment]
Hello, i created pull request as you asked in comment ... :)

**Comment by gsantner** [comment]
(I am posting this to all pull requests)

Hey! Just want to know how you are doing. Do you have issues or have questions? If you wont work on this anymore also let me know please, so I can announce to others its free to take again.
Thanks!

**Comment by Delko97** [comment]
Hey, yes i would like to have one question. Are there any preferences where to place those buttons?

**Comment by gsantner** [comment]
Another option in the CommonTextActions preffered.

You can find a arrays.xml file where all items are in (like pagup, ohm, ..etc). There add these two new options.

In the editor there is a button with "keyboard" icon, it shows the array of options.

So its wont be really a button but one of the items in that list.

**Comment by Delko97** [comment]
Hey, i have to admit I kinda forgot that i had this issue assigned :( (as an excuse for late complete i add some Slovak translations :) ).
Now to solution, basically what I did is that I selected whole current line, copied it to clipboard, then deleted that line and depending on request to move up or down pasted to line above/under.

**Comment by gsantner** [comment]
@Delko97 

Thanks for working on it!

I found a easy way to move cursor around trecently. Please have a look at the Markdown Table insert callback functiiom how it woerks
hlEditor.simulateKeyPress(KeyEvent.KEYCODE_DPAD_UP);

**Comment by Delko97** [comment]
@gsantner 

I tried using Keycode.HOME as you suggested but wasn't successfull. Maybe it is not working for all Android devices? So I just removed using clipboard and text saved to var.

**Comment by Delko97** [comment]
If you are OK with changes, you can merge to your branch... :)

**Comment by gsantner** [comment]
@Delko97 
Thanks for changes!

Feedback:
* Does it work when multiple lines are selected? Would be very nice if that works
* For counting lines, easiest way is `string.split(System.getProperty("line.separator")).length` - then you don't need loop etc

**Comment by Delko97** [comment]
@gsantner 

Hey, updated 2 points from your feedback. Regarding moving multiple lines. Sorry i wasn't successfull. Tried multiple approaches but all i got was moving of current line.

**Comment by Delko97** [comment]
@gsantner 

Hello, sorry for late but got one more idea to fix multiline moving. It is working now one line/multiline selection. You can merge if you think it is ok :)

**Comment by AndroDZ** [comment]
can you please add find and replace words or sentences feature?

**Comment by gsantner** [comment]
@AndroDZ 
This is not goal and scope of this PR.

**Comment by gsantner** [comment]
@Delko97 Thanks!

**Comment by gsantner** [comment]
@Delko97 
It didn't work for me as expected, I basically wrote an own solution that does - its here:

https://github.com/gsantner/markor/blob/d0a5103223430e7af925a48f49affa0ae64ef83b/app/src/main/java/net/gsantner/markor/format/general/CommonTextActions.java#L245

**Pull request merged**
