### PR TITLE
Add Nord colors

### PR DESCRIPTION
**Pull request by lokesh-krishna**
Adds the Nord colors as discussed in #1133.

### CODE REVIEW

**Comment by gsantner** [comment]
thanks

can you please also modify the code for it? See AppSettings.java and preferences_master.xml, should be copy-pasteable+rename from one of the exsisting ones.

**Comment by lokesh-krishna** [comment]
I edited `preferences_master.xml` but I'm not sure about what needs to be added in `AppSettings.java`. Could you point me to a reference line number?

**Comment by gsantner** [comment]
SettingsActivity

**Comment by lokesh-krishna** [comment]
Is this alright?

**Comment by gsantner** [comment]
thanks yes looks OK

**Pull request merged**
