### PR TITLE
#1174 disallow screenshots

### PR DESCRIPTION
**Pull request by Zoo-M0**
Add FLAG_SECURE to activities to avoid screenshots.

### CODE REVIEW

**Comment by gsantner** [comment]
@Zoo-M0  
I made a change and now all activites inherit from MarkorBaseActivity.  
So you can now make the change there instead.  
Note: It should be a additional settings option (preferences xml file), not "just add the flag"

**Comment by Zoo-M0** [comment]
@gsantner perfect, I will move it to the new activity, and work on the preferences flag.

**Comment by gsantner** [comment]
I reworked it a bit, merging now 

thanks! 😄

**Review by gsantner — APPROVED** [review]
I reworked it a bit, merging now 

thanks for your help 😄 

as first-time-contribution  - happy to hear more! 🎉

**Pull request merged**
