### PR TITLE
fix confusing typo in bug template

### PR DESCRIPTION
**Pull request by fabian-thomas**

### CODE REVIEW

**Comment by gsantner** [comment]
It is not a typo. By checking you should confirm that the bug IS NOT 
present on the git version.

**Comment by fabian-thomas** [comment]
@gsantner Ok, please explain that further. I had to check that box to create my issue. What is the point of that box?

**Comment by gsantner** [comment]
That you download, install and try the latest development of Markor, built from git master.

**Comment by fabian-thomas** [comment]
But that's exactly what was wrong.

The template says:
I confirm that the bug is *not* on master.

And now it says:
I confirm that the bug is *still* on master.

**Comment by gsantner** [comment]
I've cleaned it up in both templates, albeit differently than that one word change

**Pull request closed without merging**
