### PR TITLE
Add search in view mode

### PR DESCRIPTION
**Pull request by Anca07**
Solves #747 
- add searchview component
- implement search functionality in webview

Requested screenshots with light theme and markdown template file provided below:

73712538_1230374187146998_845365901631946752_n
72843522_534226883790108_7242509519094284288_n

### CODE REVIEW

**Comment by gsantner** [comment]
Where does that button come from? 
grafik

So the Enter button as well the arrow jumps to next result?

**Comment by Anca07** [comment]
The arrow button is a component of the SearchView, activated by doing this:

`searchView.setSubmitButtonEnabled(true);`

And yes, they both have the same functionality of jumping to the next result.

**Comment by gsantner** [comment]
OK!

Can you please also add onBackButtonPressed -> close search?

**Comment by gsantner** [comment]
Am I wrong or did you have the same also for EditText? How did it work there?
Potentially we can use this search also in edittext

**Comment by Anca07** [comment]
If you refer to the search in edit mode, I did not change that. 
I only implemented this type of search for view mode.

**Pull request merged**
